### ISSUE TITLE
Use the natively provided caching features in CI

### ISSUE THREAD

**Issue by ethangardner** [GSA-TTS/forms#599]
This work was started in ticket #414 with the end-to-end tests. Many of our actions do manual caching. There is an easier way to manage the cache with the provided `actions/setup-node` package. This task is to move all the actions to use the built-in version so we have less to manage.

```
- name: Install node.js version
  uses: actions/setup-node@v4
  id: install-node
  with:
      node-version-file: '.nvmrc'
      cache: 'pnpm'
      cache-dependency-path: 'pnpm-lock.yaml'
```
